"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Somya Krishna and Iniya Vidyashankar, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:sk55256
UT EID 2:iv3976
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rail = [['' for _ in range(len(string))] for _ in range(key)]
    row, step = 0, 1
    for i, char in enumerate(string):
        rail[row][i] = char
        if row == 0:
            step = 1
        elif row == key - 1:
            step = -1
        row += step
    return ''.join([''.join(r) for r in rail])

def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    rail = [['' for _ in range(len(string))] for _ in range(key)]
    row, step = 0, 1
    for i in range(len(string)):
        rail[row][i] = '*'
        if row == 0:
            step = 1
        elif row == key - 1:
            step = -1
        row += step
    idx = 0
    for r in range(key):
        for c in range(len(string)):
            if rail[r][c] == '*':
                rail[r][c] = string[idx]
                idx += 1
    result = []
    row, step = 0, 1
    for i in range(len(string)):
        result.append(rail[row][i])
        if row == 0:
            step = 1
        elif row == key - 1:
            step = -1
        row += step
    return ''.join(result)


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    return ''.join([char.lower() for char in string if char.isalpha()])


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr(((ord(s.lower()) - ord('a') + (ord(p.lower()) - ord('a'))) % 26) + ord('a'))

def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr(((ord(s.lower()) - ord('a') - (ord(p.lower()) - ord('a'))) % 26) + ord('a'))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    filtered_string = filter_string(string)
    extended_phrase = (phrase * ((len(filtered_string) // len(phrase)) + 1))[:len(filtered_string)]
    return ''.join([encode_character(p, s) for p, s in zip(extended_phrase, filtered_string)])


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    filtered_string = filter_string(string)
    if not filtered_string:
        return ""
    extended_phrase = (phrase * ((len(filtered_string) // len(phrase)) + 1))[:len(filtered_string)]
    return ''.join([decode_character(p, s) for p, s in zip(extended_phrase, filtered_string)])

def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher
    import sys
    import sys
    input_data = sys.stdin.read().splitlines()
    plaintext_rf = input_data[0]
    key_rf = int(input_data[1])
    encoded_rf = rail_fence_encode(plaintext_rf, key_rf)
    print("Rail Fence Encoded:", encoded_rf)
    decoded_rf = rail_fence_decode(encoded_rf, key_rf)
    print("Rail Fence Decoded:", decoded_rf)
    plaintext_vig = input_data[4]
    phrase_vig = input_data[5]
    encoded_vig = vigenere_encode(plaintext_vig, phrase_vig)
    print("Vigenere Encoded:", encoded_vig)
    decoded_vig = vigenere_decode(encoded_vig, phrase_vig)
    print("Vigenere Decoded:", decoded_vig)
# Do NOT modify the following code.
if __name__ == "__main__":
    main()
